draft_lab/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
from lab_1.views import index

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1,namespace='lab-1')),
    url(r'^$', index)
]

lab_1/urls.py
from django.conf.urls import url
from .views import index
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

lab_10_new/urls.py
from django.conf.urls import url
from .views import *

from .custom_auth import auth_login, auth_logout

urlpatterns = [
    # custom auth
    url(r'^custom_auth/login/$', auth_login, name='auth_login'),
    url(r'^custom_auth/logout/$', auth_logout, name='auth_logout'),

    # index dan dashboard
    url(r'^$', index, name='index'),
    url(r'^dashboard/$', dashboard, name='dashboard'),

    #movie
    url(r'^movie/list/$', movie_list, name='movie_list'),
    url(r'^movie/detail/(?P<id>.*)/$', movie_detail, name='movie_detail'),

    # Session dan Model (Watch Later)
    url(r'^movie/watch_later/add/(?P<id>.*)/$', add_watch_later, name='add_watch_later'),
    url(r'^movie/watch_later/$', list_watch_later, name='list_watch_later'),

    #API
    url(r'^api/movie/(?P<judul>.*)/(?P<tahun>.*)/$', api_search_movie, name='api_search_movie'),
]

praktikum/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic.base import RedirectView
import lab_1.urls as lab_1
import lab_2.urls as lab_2
import lab_2_addon.urls as lab_2_addon
import lab_3.urls as lab_3
import lab_4.urls as lab_4
import lab_5.urls as lab_5
import lab_6.urls as lab_6
import lab_7.urls as lab_7
import lab_8.urls as lab_8
import lab_9.urls as lab_9
import lab_10_new.urls as lab_10


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^lab-1/', include(lab_1, namespace='lab-1')),
    url(r'^lab-2/', include(lab_2, namespace='lab-2')),
    url(r'^lab-2-addon/', include(lab_2_addon, namespace='lab-2-addon')),
    url(r'^lab-3/', include(lab_3, namespace='lab-3')),
    url(r'^lab-4/', include(lab_4, namespace='lab-4')),
    url(r'^lab-5/', include(lab_5, namespace='lab-5')),
    url(r'^lab-6/', include(lab_6, namespace='lab-6')),
    url(r'^lab-7/', include(lab_7, namespace='lab-7')),
    url(r'^lab-8/', include(lab_8, namespace='lab-8')),
    url(r'^lab-9/', include(lab_9, namespace='lab-9')),
    url(r'^lab-10/', include(lab_10, namespace='lab-10-new')),
    url(r'^$', RedirectView.as_view(url='/lab-4/', permanent=True), name='index'),
]

lab_10_new/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models


class User(models.Model):
    code = models.CharField('Kode Identitas', max_length=20, primary_key=True,)
    name = models.CharField('Nama', max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class WatchLaterMovie(models.Model):
    user = models.ForeignKey(User, related_name='watch_later_movies')
    code = models.CharField("Kode Movie", max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

lab_10_new/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import json

from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .models import User
from .omdb_api import get_detail_movie, search_movie, get_movies_detail
from .custom_auth import get_user_from_session

response = {}


def index(request):
    if 'user_login' in request.session:
        return HttpResponseRedirect(reverse('lab-10-new:dashboard'))

    response['author'] = request.session.get('user_login')
    html = 'lab_10_new/login.html'
    return render(request, html, response)


def dashboard(request):
    if 'user_login' not in request.session.keys():
        return HttpResponseRedirect(reverse('lab-10-new:index'))

    response['author'] = request.session.get('user_login')
    response['identity_number'] = request.session.get('identity_number')
    response['role'] = request.session.get('role')

    identity_number = request.session.get('identity_number')

    user, created = User.objects.get_or_create(
        code=identity_number,
        defaults={
            'name': request.session.get('user_login'),
        }
    )

    movie_ids = request.session.get('movie_ids', [])
    for movie_id in movie_ids:
        user.watch_later_movies.get_or_create(code=movie_id)

    html = 'lab_10_new/dashboard.html'
    return render(request, html, response)


def movie_list(request):
    judul = request.GET.get("judul", "-")
    tahun = request.GET.get("tahun", "-")
    urlDataTables = "/lab-10/api/movie/" + judul + "/" + tahun
    jsonUrlDataTables = json.dumps(urlDataTables)
    response['jsonUrlDT'] = jsonUrlDataTables
    response['judul'] = judul
    response['tahun'] = tahun
    response['author'] = request.session.get('user_login')

    html = 'lab_10_new/movie/list.html'
    return render(request, html, response)


def movie_detail(request, id):
    response['id'] = id
    user = get_user_from_session(request)

    if user is not None:
        is_added = user.watch_later_movies.filter(code=id).count() > 0
    else:
        is_added = id in request.session.get('movies', [])

    response['is_added'] = is_added
    response['movie'] = get_detail_movie(id)
    html = 'lab_10_new/movie/detail.html'
    return render(request, html, response)


def add_watch_later(request, id):
    msg = "Berhasil tambah movie ke Watch Later"

    user = get_user_from_session(request)
    if user is not None:
        user.watch_later_movies.get_or_create(code=id)
    else:
        movies = set(request.session.get('movies', []))
        movies.add(id)
        request.session['movies'] = list(movies)

    messages.success(request, msg)
    return HttpResponseRedirect(reverse('lab-10-new:movie_detail', args=(id,)))


def list_watch_later(request):
    user = get_user_from_session(request)
    response['author'] = request.session.get('user_login')

    if user is not None:
        movie_ids = [movie.code for movie in user.watch_later_movies.all()]
    else:
        movie_ids = request.session.get('movies', [])

    watch_later_movies = get_movies_detail(movie_ids)

    response['watch_later_movies'] = watch_later_movies
    html = 'lab_10_new/movie/watch_later.html'
    return render(request, html, response)


def api_search_movie(request, judul, tahun):
    search_results = search_movie(judul, tahun)
    items = search_results

    dataJson = json.dumps({"dataku": items})
    mimetype = 'application/json'
    return HttpResponse(dataJson, mimetype)

lab_10_new/templates/lab_10_new/movie/detail.html
{% extends "lab_10_new/layout/base.html" %}

{% block content %}
<style>
    .movie-detail {
        display: flex;
        flex-direction: row;
    }
    .movie-detail .poster {
        margin: 10px;
    }
    .movie-detail .detail {
        margin: 10px;
    }
</style>
<div class="row">
    <div class="movie-detail">
        <div class="poster">
            <img src="{{ movie.Poster }}"/>
        </div>
        <div class="detail">
            <h1> {{ movie.Title }} </h1>
            <h2> Release </h2>
            <h5> {{ movie.Year }} </h5>
            <h2> Genre </h2>
            <h5> {{ movie.Genre }} </h5>
            <div class="rating">
                {% for rating in movie.Ratings %}
                    <div class="row">
                        <h4>
                            {{ rating.Source }}
                        </h4>
                        <h6>
                            {{ rating.Value }}
                        </h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <div class="box">
        {% if is_added %}
        <button class="btn btn-success"> Added to Watch Later </button>
        {% else %}
        <a href="{% url 'lab-10-new:add_watch_later' id %}" class="btn btn-warning"> Add to Watch Later </a>
        {% endif%}
    </div>

</div>
{% endblock %}

lab_10_new/templates/lab_10_new/movie/list.html
{% extends "lab_10_new/layout/base.html" %}

{% block content %}
<!-- User Login Here -->
{% if user_login %}
<a href="" class="btn btn-primary btn-lg"> Logout </a>

{% else %}
<p>
    <a href="{% url 'lab-10-new:list_watch_later' %}" class="btn btn-primary btn-lg "> Daftar <em>Watch Later </em> </a>
</p>

{% endif %}
<br>
<!-- List Movie -->
<div class="panel panel-info">
    <div class="panel-heading">
        <h2> List Movie </h2>
    </div>
    <div class="panel-body">
        <div style="margin:20px; padding:20px; background-color:lightsteelblue; border-radius:3px;">
            <form method="GET" action="{% url 'lab-10-new:movie_list' %}" class="form-inline">
                <label> Nama </label> <input type="text" class="form-control" name="judul" placeholder="Judul"
                                             value="{{judul}}">
                <label> Tahun </label> <input type="text" class="form-control" name="tahun" placeholder="Tahun "
                                              value="{{tahun}}">
                <input type="submit" class="btn btn-primary pull-right">
            </form>
        </div>
        <hr>
        <div class="table table-responsive">
            <table class="table table-hover" id="myTable" style="width: none;">
                <thead>
                <th> Judul</th>
                <th> Tahun</th>
                <th> Poster</th>
                <th> Detail</th>
                </thead>
            </table>
        </div>
    </div>
</div>

<!-- Jquery script -->
<script type="text/javascript">
    $(document).ready(function(e) {
        $('#myTable').DataTable( {
            "ajax": {
                "dataType" : 'json',
                "contentType": "application/json; charset=utf-8",
                "url": {% autoescape off %} {{ jsonUrlDT }} {% endautoescape %} ,
                "dataSrc":"dataku",
            },
            "columns" : [
                {"data" : "Title"},
                {"data" : "Year"},
                {
                    "data" : "Poster",
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        $(nTd).html("<img src='"+ oData.Poster +"' style='height:50%' class='img-responsive img-thumbnail'/>");
                    }
                },
                {
                    "data" : null,
                    "fnCreatedCell": function (nTd, sData, oData, iRow, iCol) {
                        $(nTd).html("<a href='/lab-10/movie/detail/"+ oData.imdbID +"' class='btn btn-primary'> Detail </a>");
                    }
                }
            ],
        } );
    });
</script>

{% endblock %}

lab_10_new/templates/lab_10_new/movie/watch_later.html
{% extends "lab_10_new/layout/base.html" %}

{% block content %}
<style>
    .movie-detail {
        display: flex;
        flex-direction: row;
    }
    .movie-detail .poster {
        margin: 10px;
    }
    .movie-detail .detail {
        margin: 10px;
    }
</style>
<div class="row">
    {% for movie in watch_later_movies %}
    <div class="movie-detail">
        <div class="poster">
            <img src="{{ movie.Poster }}"/>
        </div>
        <div class="detail">
            <h1> {{ movie.Title }} </h1>
            <h2> Release </h2>
            <h5> {{ movie.Year }} </h5>
            <h2> Genre </h2>
            <h5> {{ movie.Genre }} </h5>
            <div class="rating">
                {% for rating in movie.Ratings %}
                    <div class="row">
                        <h4>
                            {{ rating.Source }}
                        </h4>
                        <h6>
                            {{ rating.Value }}
                        </h6>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock %}